# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FloodRisk
                                 A QGIS plugin
 This plugin works by assessing the risk of flooding in areas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-29
        copyright            : (C) 2024 by Group 3
        email                : bsc-inf-05-20@unima.ac.mw
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Group 3'
__date__ = '2024-11-29'
__copyright__ = '(C) 2024 by Group 3'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FloodRisk class from file FloodRisk.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flood_risk_assessor import FloodRiskPlugin
    return FloodRiskPlugin()
